window.PROPERTIES = [
  {
    id: "p1",
    title: "Harborview Colonial",
    address: "18 Lothrop Street",
    city: "Beverly",
    state: "MA",
    zip: "01915",
    price: 1249000,
    beds: 4,
    baths: 3,
    sqft: 2860,
    year: 1924,
    type: "Single Family",
    district: "Beverly Public Schools",
    image: "/assets/properties/p1.jpg",
    lng: -70.8801,
    lat: 42.5588,
    featured: true
  },
  {
    id: "p2",
    title: "Marblehead Neck Residence",
    address: "42 Ocean Avenue",
    city: "Marblehead",
    state: "MA",
    zip: "01945",
    price: 2195000,
    beds: 5,
    baths: 4,
    sqft: 4120,
    year: 2008,
    type: "Single Family",
    district: "Marblehead Public Schools",
    image: "/assets/properties/p2.jpg",
    lng: -70.8432,
    lat: 42.5051,
    featured: true
  },
  {
    id: "p3",
    title: "Federal Street Townhome",
    address: "7 Federal Street",
    city: "Salem",
    state: "MA",
    zip: "01970",
    price: 875000,
    beds: 3,
    baths: 2.5,
    sqft: 2140,
    year: 1898,
    type: "Townhouse",
    district: "Salem Public Schools",
    image: "/assets/properties/p3.jpg",
    lng: -70.8956,
    lat: 42.5218,
    featured: true
  },
  {
    id: "p4",
    title: "Andover Green Colonial",
    address: "31 School Street",
    city: "Andover",
    state: "MA",
    zip: "01810",
    price: 1549000,
    beds: 5,
    baths: 3.5,
    sqft: 3680,
    year: 1996,
    type: "Single Family",
    district: "Andover Public Schools",
    image: "/assets/properties/p4.jpg",
    lng: -71.1412,
    lat: 42.6581,
    featured: true
  },
  {
    id: "p5",
    title: "Union Street Loft",
    address: "210 Union Street",
    city: "New Bedford",
    state: "MA",
    zip: "02740",
    price: 649000,
    beds: 2,
    baths: 2,
    sqft: 1680,
    year: 2019,
    type: "Condo",
    district: "New Bedford Public Schools",
    image: "/assets/properties/p5.jpg",
    lng: -70.9278,
    lat: 41.6354,
    featured: true
  },
  {
    id: "p6",
    title: "Dartmouth Farmhouse",
    address: "88 Chase Road",
    city: "Dartmouth",
    state: "MA",
    zip: "02747",
    price: 989000,
    beds: 4,
    baths: 3,
    sqft: 3020,
    year: 1978,
    type: "Single Family",
    district: "Dartmouth Public Schools",
    image: "/assets/properties/p6.jpg",
    lng: -70.9698,
    lat: 41.6139,
    featured: true
  },
  {
    id: "p7",
    title: "Manchester Cottage",
    address: "12 Bridge Street",
    city: "Manchester-by-the-Sea",
    state: "MA",
    zip: "01944",
    price: 1875000,
    beds: 4,
    baths: 3,
    sqft: 2940,
    year: 1912,
    type: "Single Family",
    district: "Manchester Essex Regional",
    image: "/assets/properties/p7.jpg",
    lng: -70.7691,
    lat: 42.5776,
    featured: false
  },
  {
    id: "p8",
    title: "North Andover Contemporary",
    address: "55 Pleasant Street",
    city: "North Andover",
    state: "MA",
    zip: "01845",
    price: 1125000,
    beds: 4,
    baths: 2.5,
    sqft: 2750,
    year: 2014,
    type: "Single Family",
    district: "North Andover Public Schools",
    image: "/assets/properties/p8.jpg",
    lng: -71.1348,
    lat: 42.6984,
    featured: true
  }
];
